"""add phone number

Revision ID: 169883b9c233
Revises: 437d379f0b99
Create Date: 2022-07-26 20:57:06.942091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169883b9c233'
down_revision = '437d379f0b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
